# Team 13
# Tom Koh 329888
# Alex Lasffre 1161899
# Vishall Krishnan 1018473
# Jothe Krishnan 1187902
# Kwanhyoung Lee 992925

---
# Create volumes from vars
- name: Create volume(s) on NeCTAR
  os_volume:
#    auth:
#      auth_url: https://keystone.rc.nectar.org.au:5000/v3/
#      username: t.koh@student.unimelb.edu.au
#      password: Yzg0NDQzMjhiYzQ4NTY4
#      project_name: "unimelb-comp90024-2"
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."
